name: Test 2 simple endpoints

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x" 
      - run: npm install
      - run: npm run unit-tests
  
  api-tests:
    name: Run docker and API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm install
      - run: docker build -t nodejs-api-test-demo .
      - run: docker run --name nodejs-api-test-demo -p 3001:3001 -d nodejs-api-test-demo
      - run: npm run api-tests
            