name: Test 2 simple endpoints

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x" 
      - run: npm install
      - run: npm test
            